AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A sample Serverless API
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: myFunction.handler
      Runtime: nodejs6.10
  